import { z } from "zod/v4";

export const baUnderwritingSchema = z
  .object({
    BA_UNDERWRITING_ID: z.number().nullable().optional(),
    POLICIES_ID: z.number().nullable().optional(),
    CANADIANCOVERAGE: z.string().nullable().optional(),
    CARRIERTYPE: z.string().nullable().optional(),
    COMPENSATEDTRIP: z.string().nullable().optional(),
    COVR: z.string().nullable().optional(),
    DISC: z.string().nullable().optional(),
    DISCPD: z.string().nullable().optional(),
    FLEET: z.string().nullable().optional(),
    HAUL: z.string().nullable().optional(),
    HIRED: z.string().nullable().optional(),
    LEASE: z.string().nullable().optional(),
    LEASEENAME: z.string().nullable().optional(),
    LEASEINS: z.string().nullable().optional(),
    LEASEOPER: z.string().nullable().optional(),
    LEASEPERECENT: z.string().nullable().optional(),
    LOCATION_TRACK: z.string().nullable().optional(),
    MAINTENANCEPROGRAM: z.string().nullable().optional(),
    MAXALLVEHICLES: z.number().nullable().optional(),
    MAXLOCATION: z.number().nullable().optional(),
    MAXVEHICLE: z.number().nullable().optional(),
    MEXICANCOVERAGE: z.string().nullable().optional(),
    MILEAGE_TRACK: z.string().nullable().optional(),
    MONITOR_DRI_SAFETY: z.string().nullable().optional(),
    MONITOR_OTHER: z.string().nullable().optional(),
    MONITOR_VEH_MAINT: z.string().nullable().optional(),
    MVR: z.string().nullable().optional(),
    NAVIGATION: z.string().nullable().optional(),
    NEXTRECEIPTS: z.number().nullable().optional(),
    NOT_OWNED_REG: z.string().nullable().optional(),
    CUSTOMIZED_ALTERED: z.string().nullable().optional(),
    ICC_PUC: z.string().nullable().optional(),
    HARMLESS_AGREE: z.string().nullable().optional(),
    FAMILY_USE: z.string().nullable().optional(),
    NOT_COV_WC: z.string().nullable().optional(),
    VEH_NOT_SCHED: z.string().nullable().optional(),
    MOVING_VIOL: z.string().nullable().optional(),
    INSPECT_VEHS: z.string().nullable().optional(),
    OTHERADDLDESCRIPTION: z.string().nullable().optional(),
    OTHERDESCRIPTION: z.string().nullable().optional(),
    OWNED: z.string().nullable().optional(),
    PASTRECEIPTS: z.number().nullable().optional(),
    PERMIT: z.string().nullable().optional(),
    PERMITPERCENT: z.string().nullable().optional(),
    RADIUSEXC: z.string().nullable().optional(),
    RATESTATE: z.string().nullable().optional(),
    RECEIPTS: z.string().nullable().optional(),
    REGULARPHYSICAL: z.string().nullable().optional(),
    TARGETCOMMODITY: z.string().nullable().optional(),
    TELEMATICS: z.string().nullable().optional(),
    TELEMATICS_PERCENT: z.number().nullable().optional(),
    TETINGPROGRAM: z.string().nullable().optional(),
    TRACK_FUEL: z.string().nullable().optional(),
    TRAININGPROGRAM: z.string().nullable().optional(),
    URISEQ: z.string().nullable().optional(),
    USCOVERAGE: z.string().nullable().optional(),
    WORKCOMP: z.string().nullable().optional(),
    OVER_50_USE: z.string().nullable().optional(),
  })
  .meta({
    description: "Auto underwriting from Sagitta table 'BA_UNDERWRITING'",
    sagittaTable: "BA_UNDERWRITING",
  });

export type BAUnderwritingSchema = z.infer<typeof baUnderwritingSchema>;
