import { z } from 'zod/v4';

export enum FolderTypes {
  accounting = 'accounting',
  aiPolicyVerification = 'aiPolicyVerification',
  applications = 'applications',
  appraisals = 'appraisals',
  auditsAuditCorrespondence = 'auditsAuditCorrespondence',
  auditsExpMods = 'auditsExpMods',
  binding = 'binding',
  blueFolder = 'blueFolder',
  carrier = 'carrier',
  cbd = 'cbd',
  cbdDoc = 'cbdDoc',
  certificates = 'certificates',
  checklistWorksheet = 'checklistWorksheet',
  claimLoss = 'claimLoss',
  claims = 'claims',
  claimsCorrespondence = 'claimsCorrespondence',
  claimsReview = 'claimsReview',
  clientCorrespondence = 'clientCorrespondence',
  contractCorrespondence = 'contractCorrespondence',
  contractAgreement = 'contractAgreement',
  declinations = 'declinations',
  engage = 'engage',
  engagement = 'engagement',
  expModExpModCorrespondence = 'expModExpModCorrespondence',
  flood = 'flood',
  lcRecommendationsVisits = 'lcRecommendationsVisits',
  lcTraining = 'lcTraining',
  lossRunCorrespondence = 'lossRunCorrespondence',
  lossRunCorrespondenceBmb = 'lossRunCorrespondenceBmb',
  lossRunCorrespondenceRsp = 'lossRunCorrespondenceRsp',
  lossRuns = 'lossRuns',
  managedCareMedicalBills = 'managedCareMedicalBills',
  market = 'market',
  masterPriorHistoryLossSummary = 'masterPriorHistoryLossSummary',
  newMail = 'newMail',
  permanentFile = 'permanentFile',
  policies = 'policies',
  policy = 'policy',
  policyCheckingDocuments = 'policyCheckingDocuments',
  policyCorrespondence = 'policyCorrespondence',
  policyTerm = 'policyTerm',
  proposalAttachments = 'proposalAttachments',
  proposalShell = 'proposalShell',
  proposals = 'proposals',
  quotes = 'quotes',
  rateAnalysis = 'rateAnalysis',
  recommendations = 'recommendations',
  revisions = 'revisions',
  riskMgt = 'riskMgt',
  rsp = 'rsp',
  submission = 'submission',
  submissions = 'submissions',
  submissionCorrespondence = 'submissionCorrespondence',
  submissionCorrespondenceClSvc = 'submissionCorrespondenceClSvc',
}

export const getFoldersDto = z.object({
  clientId: z.coerce.number(),
  folderTypes: z.enum(FolderTypes).array().optional().nullable(),
  folderId: z.coerce.number().optional().nullable(),
});

export type GetFoldersDto = z.infer<typeof getFoldersDto>;
