import { z } from "zod/v4";

export const eqCoveragesSchema = z
  .object({
    EQ_COVERAGES_ID: z.number().optional(),
    BUILDINGDESC: z.string().optional(),
    BUILDINGNO: z.number().optional(),
    CASTASTOPHLIMPEREVENT: z.number().optional(),
    COVSEQ: z.string().optional(),
    DATEOFF: z.date().optional(),
    DEDANNUALAGGREGATE: z.number().optional(),
    DEDFLATDOLLARAMOUNT: z.number().optional(),
    DEDFUTURELOSSAFTERANNAGG: z.string().optional(),
    DEDPERCENTAGEMAXIMUM: z.number().optional(),
    DEDPERCENTAGEMINIMUM: z.number().optional(),
    DEDPERCENTAGEOFEQUIPMENTVALUE: z.string().optional(),
    SCHEDADDLINTERESTSEQ: z.number().optional(),
    EQFLOODCASTASTROPHELOSSAMOUNT: z.number().optional(),
    EQUIPMENTBLANKETAMOUNT: z.number().optional(),
    EQUIPMENTCOINSPERCENTAGE: z.string().optional(),
    LASTEFFDATE: z.date().optional(),
    LASTENTRYDATE: z.date().optional(),
    LASTUSER: z.string().optional(),
    LOCATIONS_ID: z.number().optional(),
    NONREPORTING: z.string().optional(),
    NONREPORTINGFIRSTRATE: z.number().optional(),
    NONREPORTINGNDRATE: z.number().optional(),
    NONREPORTINGPREMIUM: z.number().optional(),
    POLICIES_ID: z.number().optional(),
    PROPERTYATACQUIREDLOCATIONS: z.number().optional(),
    PROPERTYCOVEREDATALLLOCATIONS: z.number().optional(),
    PROPERTYINTRANSIT: z.number().optional(),
    PROPNOTATPREMISESNOTONSHED: z.number().optional(),
    REPORTING: z.string().optional(),
    REPORTINGADJUSTMENTPERIOD: z.string().optional(),
    REPORTINGDEPOSITPREMIUM: z.number().optional(),
    REPORTINGFIRSTPREMBASE: z.string().optional(),
    REPORTINGFIRSTRATE: z.number().optional(),
    REPORTINGMINIMUMANNPREMIUM: z.number().optional(),
    REPORTINGREPORTINGPERIOD: z.string().optional(),
    REPORTINGSECONDPREMBASE: z.string().optional(),
    REPORTINGSECONDRATE: z.number().optional(),
    REPORTINGTHIRDPREMBASE: z.string().optional(),
    SCHEDULENO: z.number().optional(),
  })
  .meta({
    description: "Equipment coverages from Sagitta table 'EQ_COVERAGES'",
    sagittaTable: "EQ_COVERAGES",
  });

export type EQCoveragesSchema = z.infer<typeof eqCoveragesSchema>;
