import { CoverageCode } from "@bmb-inc/types";

export const coverageCodes: Record<
  string,
  { coverageCode: CoverageCode; coverageDesc: string }
> = {
  // '325': { coverageCode: '125', coverageDesc: '	Section 125' },
  // '342': { coverageCode: '401', coverageDesc: '	Financial Products-401K' },
  // '343': { coverageCode: '457', coverageDesc: '	Financial Products-457' },
  // '344': { coverageCode: '529', coverageDesc: '	Financial Products-529' },
  "398": { coverageCode: CoverageCode.ACC, coverageDesc: "	Accident" },
  // '31': { coverageCode: 'ACM', coverageDesc: '	Account Master' },
  // '313': { coverageCode: 'ADD', coverageDesc: '	AD&D' },
  // '424': { coverageCode: 'ADM', coverageDesc: '	Benefits Admin Svc Fee' },
  // '29': { coverageCode: 'AE2', coverageDesc: '	AEnterprise 2000' },
  // '56': { coverageCode: 'AIR', coverageDesc: '	Aviation-Commercial' },
  // '399': { coverageCode: 'ANA', coverageDesc: '	Claims Analyzer' },
  // '291': { coverageCode: 'ANI', coverageDesc: '	Animal Mortality-COMML' },
  // '280': { coverageCode: 'ANL', coverageDesc: '	Individual Annuity' },
  // '71': { coverageCode: 'ANM', coverageDesc: '	Animal Mortality-PL' },
  // '157': { coverageCode: 'ANN', coverageDesc: '	Pension-Prof.Shrg Annuity' },
  "85": {
    coverageCode: CoverageCode.APP,
    coverageDesc: "	Applicant-Commercial",
  },
  // '63': { coverageCode: 'ARA', coverageDesc: '	Assigned Risk Auto-Persnl' },
  // '69': { coverageCode: 'ARP', coverageDesc: '	A/R Valuable Papers' },
  // '205': { coverageCode: 'ASB', coverageDesc: '	Asbestos Abatement Liab.' },
  // '217': { coverageCode: 'ASF', coverageDesc: '	Agency Service Fee' },
  // '86': { coverageCode: 'AUO', coverageDesc: '	Auto-Out of State-Comml' },
  "3": { coverageCode: CoverageCode.AUT, coverageDesc: "Auto-Personal" },
  // '353': { coverageCode: 'BAD', coverageDesc: '	Benefits Administration' },
  // '177': { coverageCode: 'BBB', coverageDesc: '	Bankers Blanket Bond' },
  "167": { coverageCode: CoverageCode.BCO, coverageDesc: "	Bonds-Contract" },
  "67": {
    coverageCode: CoverageCode.BDR,
    coverageDesc: "	Bldrs Risk/Installation",
  },
  "131": {
    coverageCode: CoverageCode.BEN,
    coverageDesc: "	Employee Benefits Liab.",
  },
  // '10': { coverageCode: 'BGL', coverageDesc: '	Burglary and Robbery' },
  // '87': { coverageCode: 'BLE', coverageDesc: '	Bailees' },
  // '54': { coverageCode: 'BLI', coverageDesc: '	Business Life' },
  "135": { coverageCode: CoverageCode.BLK, coverageDesc: "	Construction Block" },
  "11": {
    coverageCode: CoverageCode.BLR,
    coverageDesc: "	Boiler and Machinery",
  },
  "169": {
    coverageCode: CoverageCode.BMI,
    coverageDesc: "	Bonds-Miscellaneous",
  },
  // '419': { coverageCode: 'BMO', coverageDesc: '	Bonds-Misc Other' },
  "168": { coverageCode: CoverageCode.BNO, coverageDesc: "	Bonds-Notary" },
  "4": { coverageCode: CoverageCode.BOA, coverageDesc: "Watercraft-Personal" },
  // '426': { coverageCode: 'BOD', coverageDesc: '	Bonds On Demand' },
  "12": { coverageCode: CoverageCode.BOP, coverageDesc: "	Business Owners" },
  // '366': { coverageCode: 'BOT', coverageDesc: '	Benefits- Other' },
  "323": {
    coverageCode: CoverageCode.BTA,
    coverageDesc: "	Business Travel Accident",
  },
  // '324': { coverageCode: 'BTM', coverageDesc: '	Business Travel Medical' },
  // '164': { coverageCode: 'CAF', coverageDesc: '	Cafeteria Plan' },
  // '396': { coverageCode: 'CAN', coverageDesc: '	Cancer Coverage' },
  // '13': { coverageCode: 'CAR', coverageDesc: '	Assigned Risk Auto-Comml' },
  "14": { coverageCode: CoverageCode.CAU, coverageDesc: "	Auto-Commercial" },
  // '200': { coverageCode: 'CBB', coverageDesc: '	Combined Blanket Bond' },
  "90": {
    coverageCode: CoverageCode.CBI,
    coverageDesc: "	Business Interruption",
  },
  // '354': { coverageCode: 'CCA', coverageDesc: '	COBRA Compliance Audit' },
  // '146': { coverageCode: 'CFE', coverageDesc: '	Consulting Fee' },
  "100": { coverageCode: CoverageCode.CFL, coverageDesc: "	Flood-Commercial" },
  "98": {
    coverageCode: CoverageCode.CFO,
    coverageDesc: "	Farmowners-Commercial",
  },
  // '203': { coverageCode: 'CHA', coverageDesc: "	Charterer's Legal Liab." },
  "120": {
    coverageCode: CoverageCode.CIM,
    coverageDesc: "	Combined Inland Marine",
  },
  // '214': { coverageCode: 'CLM', coverageDesc: '	Claims Mgt Fees' },
  // '185': { coverageCode: 'COB', coverageDesc: '	Fee for Svc - Cobra Admin' },
  "73": { coverageCode: CoverageCode.CON, coverageDesc: "	Condominium" },
  // '267': { coverageCode: 'CP	', coverageDesc: '*ComlProp-PRIOR HIST ONLY' },
  // '190': { coverageCode: 'CPE', coverageDesc: '	Excess Property-Comml' },
  // '114': { coverageCode: 'CPG', coverageDesc: '	Package-Construction' },
  // '247': { coverageCode: 'CPJ', coverageDesc: '	Property-Joint Policy-Com' },
  "274": {
    coverageCode: CoverageCode.CPL,
    coverageDesc: "	Contractors Pollution",
  },
  "30": { coverageCode: CoverageCode.CPP, coverageDesc: "	Property-Commercial" },
  // '140': { coverageCode: 'CPS', coverageDesc: '	Property-Out of State-Com' },
  // '89': { coverageCode: 'CRE', coverageDesc: '	Credit Insurance' },
  "1": { coverageCode: CoverageCode.CRM, coverageDesc: "Crime" },
  // '92': { coverageCode: 'CRO', coverageDesc: '	Crop Floater' },
  // '326': { coverageCode: 'CSV', coverageDesc: '	Compliance Services' },
  "88": {
    coverageCode: CoverageCode.CWA,
    coverageDesc: "	Watercraft-Commercial",
  },
  "204": {
    coverageCode: CoverageCode.CWE,
    coverageDesc: "	Windstorm-Excess-Comml",
  },
  "99": {
    coverageCode: CoverageCode.CWI,
    coverageDesc: "	Windstorm-Commercial",
  },
  "404": { coverageCode: CoverageCode.CYB, coverageDesc: "	Cyber Liability" },
  "94": {
    coverageCode: CoverageCode["D_O"],
    coverageDesc: "	Directors & Officers",
  },
  // '315': { coverageCode: 'DBL', coverageDesc: '	New York DBL' },
  // '327': { coverageCode: 'DBP', coverageDesc: '	Defined Benefit Plan' },
  // '332': { coverageCode: 'DCI', coverageDesc: '	Disease/Critical Illness' },
  // '329': { coverageCode: 'DEA', coverageDesc: '	Dependent Eligibility Aud' },
  "220": {
    coverageCode: CoverageCode.DED,
    coverageDesc: "	Deductible Buy Down",
  },
  "184": { coverageCode: CoverageCode.DEN, coverageDesc: "	Individual Dental" },
  // '93': { coverageCode: 'DIC', coverageDesc: '	Difference in Cond-Comml' },
  // '305': { coverageCode: 'DIN', coverageDesc: '	Dental Indemnity' },
  // '287': { coverageCode: 'DIP', coverageDesc: '	Difference In Cond-PL' },
  // '147': { coverageCode: 'DIS', coverageDesc: '	Disability Income' },
  // '330': { coverageCode: 'DLI', coverageDesc: '	Dependent Life' },
  // '216': { coverageCode: 'DOE', coverageDesc: '	D&O/E&O Package' },
  // '328': { coverageCode: 'DOT', coverageDesc: '	Dental - Other' },
  "218": { coverageCode: CoverageCode.DPK, coverageDesc: "	D&O Package" },
  // '331': { coverageCode: 'DPO', coverageDesc: '	Disability Plans - Other' },
  "303": { coverageCode: CoverageCode.DPP, coverageDesc: "	Dental PPO" },
  // '304': { coverageCode: 'DTO', coverageDesc: '	Dental Triple Option' },
  // '5': { coverageCode: 'DWL	', coverageDesc: 'Dwelling Fire-Personal' },
  // '97': { coverageCode: 'E&O', coverageDesc: '	Errors & Omissions' },
  // '232': { coverageCode: 'EAP', coverageDesc: '	Employee Asst Plans' },
  // '440': { coverageCode: 'EAR', coverageDesc: '	Earthquake-Personal Lines' },
  // '209': { coverageCode: 'EBB', coverageDesc: '	Excess Blanket Bond' },
  // '242': { coverageCode: 'ECA', coverageDesc: '	Auto-Commercial Excess' },
  "435": { coverageCode: CoverageCode.EDO, coverageDesc: "	Excess D&O Package" },
  "96": {
    coverageCode: CoverageCode.EDP,
    coverageDesc: "	Electronic Data Policy",
  },
  // '335': { coverageCode: 'EDS', coverageDesc: '	EXB - Dis Supp Exec Ben' },
  "257": {
    coverageCode: CoverageCode.EEO,
    coverageDesc: "	Excess Errors & Omissions",
  },
  // '258': { coverageCode: 'EFD', coverageDesc: '	Excess Fidelity' },
  "197": {
    coverageCode: CoverageCode.EFL,
    coverageDesc: "	Flood-Excess-Personal ",
  },
  // '261': { coverageCode: 'EGA', coverageDesc: '	Excess Garage Liability' },
  // '246': { coverageCode: 'EHR', coverageDesc: '	Eesis Human Resource Fee' },
  // '333': { coverageCode: 'EIA', coverageDesc: '	Equity Indexed Annuity' },
  // '256': { coverageCode: 'EKI', coverageDesc: '	Kidnap & Ransom - EXCESS' },
  // '264': { coverageCode: 'EL	', coverageDesc: 'Employers Liability' },
  "250": { coverageCode: CoverageCode.ELP, coverageDesc: "	EPL Package" },
  // '196': { coverageCode: 'EMP', coverageDesc: '	Employee Leasing Contract' },
  // '226': { coverageCode: 'EPK', coverageDesc: '	Errors & Omissions Pkg' },
  "136": {
    coverageCode: CoverageCode.EPL,
    coverageDesc: "	Employment Practices Liab",
  },
  "68": { coverageCode: CoverageCode.EQF, coverageDesc: "	Equipment Floater" },
  "279": { coverageCode: CoverageCode.ERI, coverageDesc: "	ERISA Bond" },
  // '336': { coverageCode: 'ERP', coverageDesc: '	EXB-Exec Retirement Plans' },
  // '198': { coverageCode: 'EWI', coverageDesc: '	Windstorm-Excess-Personal' },
  // '239': { coverageCode: 'EWR', coverageDesc: '	War Risk Insurance-Excess' },
  // '334': { coverageCode: 'EXB', coverageDesc: '	Executive Benefits' },
  // '138': { coverageCode: 'EXE', coverageDesc: '	Package-Executive' },
  // '193': { coverageCode: 'EXP', coverageDesc: '	Exporters Package' },
  "289": { coverageCode: CoverageCode.FAP, coverageDesc: "	Farm Auto Personal" },
  "75": { coverageCode: CoverageCode.FAR, coverageDesc: "	Farmowners-Personal" },
  // '125': { coverageCode: 'FAU', coverageDesc: '	Foreign Auto ' },
  // '245': { coverageCode: 'FCP', coverageDesc: '	Foreign Property' },
  "130": {
    coverageCode: CoverageCode.FDC,
    coverageDesc: "	Fiduciary Liability",
  },
  // '341': { coverageCode: 'FEE', coverageDesc: '	**DO NOT USE**' },
  // '124': { coverageCode: 'FGL', coverageDesc: '	Foreign General Liability' },
  "15": { coverageCode: CoverageCode.FID, coverageDesc: "	Fidelity Coverage" },
  // '16': { coverageCode: 'FIR', coverageDesc: '	Comm. Fire & Allied Peril' },
  "236": {
    coverageCode: CoverageCode.FLE,
    coverageDesc: "	Flood-Excess-Commercial",
  },
  // '104': { coverageCode: 'FLI', coverageDesc: '	Farm Liability-Comml' },
  // '346': { coverageCode: 'FML', coverageDesc: '	FMLA Admin' },
  "127": { coverageCode: CoverageCode.FPK, coverageDesc: "	Foreign Package" },
  // '347': { coverageCode: 'FSA', coverageDesc: '	FSA Admin' },
  // '126': { coverageCode: 'FWC', coverageDesc: '	Foreign Workers Comp.' },
  // '259': { coverageCode: 'GAD', coverageDesc: '	Group Acc Death & Dismemb' },
  // '132': { coverageCode: 'GAP', coverageDesc: '	Stop Gap Coverage' },
  "17": {
    coverageCode: CoverageCode.GAR,
    coverageDesc: "	Garage & Dealers Liab.",
  },
  // '348': { coverageCode: 'GBT', coverageDesc: '	Global Business Trav Acc' },
  "158": { coverageCode: CoverageCode.GDE, coverageDesc: "	Group Dental" },
  // '160': { coverageCode: 'GDI', coverageDesc: '	Group LTD Disability' },
  // '101': { coverageCode: 'GKL', coverageDesc: '	Garage Keepers Legal Liab' },
  // '268': { coverageCode: 'GL	', coverageDesc: '*GL-PRIOR HISTORY ONLY' },
  "260": {
    coverageCode: CoverageCode.GLA,
    coverageDesc: "	General Liab. Incl Auto",
  },
  "18": { coverageCode: CoverageCode.GLI, coverageDesc: "	General Liability" },
  "288": { coverageCode: CoverageCode.GLP, coverageDesc: "	Gen Liab-PL Only" },
  // '70': { coverageCode: 'GLS', coverageDesc: '	Glass & Sign-Commercial' },
  "170": {
    coverageCode: CoverageCode.GPK,
    coverageDesc: "	Garage & Dealers Package",
  },
  "155": { coverageCode: CoverageCode.GRL, coverageDesc: "	Group Life" },
  // '154': { coverageCode: 'GRO', coverageDesc: '	Group' },
  // '55': { coverageCode: 'GRP', coverageDesc: '	Group Medical/Dental' },
  // '161': { coverageCode: 'GST', coverageDesc: '	Group STD Disability' },
  // '310': { coverageCode: 'GTL', coverageDesc: '	Group Term Life' },
  // '162': { coverageCode: 'GVL', coverageDesc: '	Group Vol Life' },
  // '227': { coverageCode: 'HAN', coverageDesc: '	Hangarkeepers Liability' },
  "151": { coverageCode: CoverageCode.HEA, coverageDesc: "	Individual Health" },
  // '351': { coverageCode: 'HHA', coverageDesc: '	HSA/HRA Admin' },
  "409": {
    coverageCode: CoverageCode.HNO,
    coverageDesc: "	Auto-Hired/NonOwned Only",
  },
  "61": { coverageCode: CoverageCode.HOM, coverageDesc: "	Homeowners" },
  // '350': { coverageCode: 'HOS', coverageDesc: '	Hospitalization Only' },
  // '300': { coverageCode: 'HRA', coverageDesc: '	Health Reimb Arrangement' },
  // '301': { coverageCode: 'HSA', coverageDesc: '	Health Savings Account' },
  // '352': { coverageCode: 'IAC', coverageDesc: '	Individual Accident' },
  // '358': { coverageCode: 'IBE', coverageDesc: '	International Benefits' },
  // '355': { coverageCode: 'IDI', coverageDesc: '	Individual Disability' },
  // '433': { coverageCode: 'IDT', coverageDesc: '	Identity Theft' },
  // '400': { coverageCode: 'ILL', coverageDesc: '	Critical Illness' },
  "340": { coverageCode: CoverageCode.ILT, coverageDesc: "	Ind Long Term Care" },
  // '356': { coverageCode: 'IME', coverageDesc: '	Individual Medical' },
  "53": {
    coverageCode: CoverageCode.IND,
    coverageDesc: "	Individual Term Life",
  },
  // '208': { coverageCode: 'INE', coverageDesc: '	Excess Insolvency Cov.' },
  // '181': { coverageCode: 'INS', coverageDesc: '	Insolvency Coverage' },
  "401": { coverageCode: CoverageCode.INT, coverageDesc: "	Int'l Bundled Plan" },
  // '357': { coverageCode: 'IPO', coverageDesc: '	Individual Products-Other' },
  // '152': { coverageCode: 'IRA', coverageDesc: '	IRA-Keough' },
  // '282': { coverageCode: 'IVI', coverageDesc: '	Individual Vision' },
  // '102': { coverageCode: 'KID', coverageDesc: '	Kidnap & Ransom' },
  "395": {
    coverageCode: CoverageCode.KIP,
    coverageDesc: "	Kidnap & Ransom-PERSONAL",
  },
  "309": { coverageCode: CoverageCode.LAD, coverageDesc: "	Life and AD&D" },
  // '306': { coverageCode: 'LB1', coverageDesc: '	Limited Benefit 1-Tier' },
  // '307': { coverageCode: 'LB2', coverageDesc: '	Limited Benefit 2-Tier' },
  // '410': { coverageCode: 'LEG', coverageDesc: '	Legal Services' },
  "106": { coverageCode: CoverageCode.LIQ, coverageDesc: "	Liquor Liability" },
  // '376': { coverageCode: 'LIV', coverageDesc: '	Variable Life' },
  "145": { coverageCode: CoverageCode.LOS, coverageDesc: "	Loss Control" },
  // '337': { coverageCode: 'LSE', coverageDesc: '	EXB-Life Supp Exec Ben' },
  // '228': { coverageCode: 'LTC', coverageDesc: '	Long Term Care' },
  "314": {
    coverageCode: CoverageCode.LTD,
    coverageDesc: "	Long Term Disability",
  },
  // '338': { coverageCode: 'LTS', coverageDesc: '	EXB-LTC Supp Exec Ben' },
  // '361': { coverageCode: 'MAD', coverageDesc: '	Medicare Advantage' },
  "19": {
    coverageCode: CoverageCode.MAR,
    coverageDesc: "	Inland Marine Fltr-Comml",
  },
  // '171': { coverageCode: 'MCR', coverageDesc: '	Misc. Crime Policy' },
  "233": {
    coverageCode: CoverageCode.MCS,
    coverageDesc: "	Medicare Supplement-Indiv",
  },
  // '362': { coverageCode: 'MDD', coverageDesc: '	Medicare Part D' },
  "302": { coverageCode: CoverageCode.MDE, coverageDesc: "	Managed Dental" },
  // '349': { coverageCode: 'MED', coverageDesc: '	Global Medical' },
  // '430': { coverageCode: 'MEX', coverageDesc: '	Short Term Mexico Coverag' },
  "143": {
    coverageCode: CoverageCode.MGL,
    coverageDesc: "	Gen. Liab.-Comprehensive",
  },
  // '393': { coverageCode: 'MGT', coverageDesc: '	Risk Management' },
  "293": { coverageCode: CoverageCode.MHM, coverageDesc: "	Medical HMO" },
  "20": {
    coverageCode: CoverageCode.MIC,
    coverageDesc: "	Misc. Commercial Line",
  },
  // '298': { coverageCode: 'MIN', coverageDesc: '	Medical Indemnity' },
  "60": {
    coverageCode: CoverageCode.MIP,
    coverageDesc: "	Misc. Personal Coverages",
  },
  // '411': { coverageCode: 'MIS', coverageDesc: '	Miscellaneous' },
  // '153': { coverageCode: 'MLI', coverageDesc: '	Mortgage Life' },
  "57": { coverageCode: CoverageCode.MOB, coverageDesc: "	Mobile Homeowners" },
  // '213': { coverageCode: 'MOC', coverageDesc: '	Mobile Homeowners-Comml' },
  "79": { coverageCode: CoverageCode.MOT, coverageDesc: "	Motorcycle-Personal" },
  // '297': { coverageCode: 'MP2', coverageDesc: '	Medical POS(2 Tier)' },
  // '295': { coverageCode: 'MP3', coverageDesc: '	Medical PPO(3-Tier)' },
  "270": { coverageCode: CoverageCode.MPK, coverageDesc: "	Marine Package" },
  "294": { coverageCode: CoverageCode.MPP, coverageDesc: "	Medical PPO" },
  // '360': { coverageCode: 'MPR', coverageDesc: '	Medical Plan Riders' },
  // '142': { coverageCode: 'MTC', coverageDesc: '	Cargo-Motor Truck' },
  "110": { coverageCode: CoverageCode.MTI, coverageDesc: "	Maritime" },
  // '425': { coverageCode: 'MTR', coverageDesc: '	Motor Carrier' },
  // '363': { coverageCode: 'MUT', coverageDesc: '	Mutual Fund' },
  // '364': { coverageCode: 'NQP', coverageDesc: '	Non-Qualified Plan' },
  // '165': { coverageCode: 'OAC', coverageDesc: '	Occupational Accident' },
  "117": {
    coverageCode: CoverageCode.OCP,
    coverageDesc: "	Owners Contractors Prot.",
  },
  // '91': { coverageCode: 'OFF', coverageDesc: '	Public Officials Bond' },
  // '113': { coverageCode: 'OLP', coverageDesc: '	Oil Lease Property' },
  "21": { coverageCode: CoverageCode.OMA, coverageDesc: "	Cargo-Ocean Marine" },
  // '365': { coverageCode: 'OMC', coverageDesc: '	Onsite Medical Center' },
  // '121': { coverageCode: 'OPK', coverageDesc: '	Package-Out of State' },
  // '345': { coverageCode: 'OTH', coverageDesc: '	Financial Products-Others' },
  // '128': {
  //   coverageCode: CoverageCode.PIP,
  //   coverageDesc: '	Protection & Indemnity',
  // },
  // '72': { coverageCode: 'PAV', coverageDesc: '	Aviation-Personal' },
  "82": {
    coverageCode: CoverageCode.PBR,
    coverageDesc: "	Builders Risk-Personal",
  },
  // '436': { coverageCode: 'PCY', coverageDesc: '	Personal Cyber Liability' },
  // '402': { coverageCode: 'PDC', coverageDesc: '	Prescription Disc Card' },
  // '321': { coverageCode: 'PDI', coverageDesc: '	Puerto Rico TDI' },
  "159": {
    coverageCode: CoverageCode.PEN,
    coverageDesc: "	Pension/401K-BENEFITS",
  },
  "219": { coverageCode: CoverageCode.PEO, coverageDesc: "	PEO" },
  // '281': { coverageCode: 'PER', coverageDesc: '	Individual Life-Permanent' },
  "149": {
    coverageCode: CoverageCode.PFA,
    coverageDesc: "	Personal Farm Liability",
  },
  "290": {
    coverageCode: CoverageCode.PFE,
    coverageDesc: "	Personal Farm Excess Liab",
  },
  "77": { coverageCode: CoverageCode.PFL, coverageDesc: "	Flood-Personal" },
  // '83': { coverageCode: 'PGL', coverageDesc: '	Glass-Personal' },
  "76": {
    coverageCode: CoverageCode.PIM,
    coverageDesc: "	Inland Marine-Personal",
  },
  "137": {
    coverageCode: CoverageCode.PKC,
    coverageDesc: "	Package-Combination-NO GL",
  },
  "22": { coverageCode: CoverageCode.PKG, coverageDesc: "	Package-Commercial" },
  "285": {
    coverageCode: CoverageCode.PKM,
    coverageDesc: "	Package - Miscellaneous",
  },
  "175": {
    coverageCode: CoverageCode.PKN,
    coverageDesc: "	Package-Pollution NO GL",
  },
  "276": {
    coverageCode: CoverageCode.PKP,
    coverageDesc: "	Package-Pollution w/GL",
  },
  "148": { coverageCode: CoverageCode.PLB, coverageDesc: "	Personal Liability" },
  // '428': { coverageCode: 'PLG', coverageDesc: '	Group Personal Lines Cov' },
  // '273': { coverageCode: 'PLL', coverageDesc: '	Pollution Legal Liability' },
  "118": {
    coverageCode: CoverageCode.POL,
    coverageDesc: "	Pollution Liability-Other",
  },
  "84": {
    coverageCode: CoverageCode.PPK,
    coverageDesc: "	Package Policy-Personal",
  },
  // '438': { coverageCode: 'PRC', coverageDesc: '	Product Recall' },
  // '141': { coverageCode: 'PRD', coverageDesc: '	Products Liability' },
  "243": {
    coverageCode: CoverageCode.PRF,
    coverageDesc: "	Professional Package",
  },
  // '222': { coverageCode: 'PRG', coverageDesc: '	Professional Incl GL' },
  "248": {
    coverageCode: CoverageCode.PRM,
    coverageDesc: "	Professional/Medical",
  },
  "23": {
    coverageCode: CoverageCode.PRO,
    coverageDesc: "	Professional Liability",
  },
  // '176': { coverageCode: 'PRS', coverageDesc: '	Prospect' },
  // '133': { coverageCode: 'PWC', coverageDesc: '	Non-Subscriber WC-Primary' },
  // '299': { coverageCode: 'PXD', coverageDesc: '	Presc. Drug(CarveOut)' },
  // '95': { coverageCode: 'QUA', coverageDesc: '	Earthquake-Commercial' },
  // '223': { coverageCode: 'R&W', coverageDesc: '	Representations & Warr.' },
  // '367': { coverageCode: 'RAD', coverageDesc: '	Risk/Acc/Disability Plans' },
  // '178': { coverageCode: 'RBB', coverageDesc: '	Brokers Blanket Bond' },
  // '237': { coverageCode: 'RCC', coverageDesc: '	Recreational Vehicle-Coml' },
  // '318': { coverageCode: 'RDI', coverageDesc: '	Rhode Island TDI' },
  "80": {
    coverageCode: CoverageCode.REC,
    coverageDesc: "	Recreational Vehicle-Pers",
  },
  "439": { coverageCode: CoverageCode.RMC, coverageDesc: "	Risk Mgt Center" },
  "105": {
    coverageCode: CoverageCode.RRP,
    coverageDesc: "	Railroad Protective Liab.",
  },
  // '115': { coverageCode: 'RSK', coverageDesc: '	Political Risks Policy' },
  // '224': { coverageCode: 'RWE', coverageDesc: '	Excess Represent.& Warr.' },
  // '173': { coverageCode: 'SBC', coverageDesc: '	Special Buyer Credit Lmts' },
  // '320': { coverageCode: 'SDI', coverageDesc: '	California SDI' },
  // '210': { coverageCode: 'SHP', coverageDesc: '	Ship Repairers Legal Liab' },
  // '24': { coverageCode: 'SMP', coverageDesc: '	Special Multi Peril' },
  // '369': { coverageCode: 'SPD', coverageDesc: '	Single Prem Def Annuity' },
  // '215': { coverageCode: 'SPE', coverageDesc: '	Special Events' },
  // '370': { coverageCode: 'SPI', coverageDesc: '	Single Prem Immed Annuity' },
  "2": {
    coverageCode: CoverageCode.STD,
    coverageDesc: "Short Term Disability",
  },
  // '308': { coverageCode: 'STL', coverageDesc: '	Stop Loss' },
  "368": { coverageCode: CoverageCode.STM, coverageDesc: "	Short Term Medical" },
  "108": { coverageCode: CoverageCode.STO, coverageDesc: "	Stock & Equipment" },
  // '234': { coverageCode: 'SUP', coverageDesc: '	Supplemental Policies-Grp' },
  // '25': { coverageCode: 'SUR', coverageDesc: '	Surety Bonds' },
  // '166': { coverageCode: 'TAC', coverageDesc: '	Travel Accident' },
  // '316': { coverageCode: 'TDB', coverageDesc: '	New Jersey TDB' },
  // '317': { coverageCode: 'TDI', coverageDesc: '	Hawaii TDI' },
  // '415': { coverageCode: 'TEL', coverageDesc: '	Telehealth' },
  "78": { coverageCode: CoverageCode.TEN, coverageDesc: "	Homeowners-Tenant" },
  // '296': { coverageCode: 'TMP', coverageDesc: '	Tiered Benefit Med PPO' },
  // '371': { coverageCode: 'TOB', coverageDesc: '	Tobacco Policy' },
  // '441': { coverageCode: 'TPK', coverageDesc: '	Transit Package' },
  "116": { coverageCode: CoverageCode.TRK, coverageDesc: "	Truckers Policy" },
  "201": { coverageCode: CoverageCode.TRN, coverageDesc: "	Transportation" },
  // '109': { coverageCode: 'TRV', coverageDesc: '	Travel Insurance-Comml' },
  // '195': { coverageCode: 'TT	', coverageDesc: 'Travel Trailer Policy' },
  "81": {
    coverageCode: CoverageCode.TVL,
    coverageDesc: "	Travel Insurance-Personal",
  },
  // '374': { coverageCode: 'UJG', coverageDesc: '	Universal Life-Joint Gtd' },
  // '372': { coverageCode: 'ULG', coverageDesc: '	Universal Life-Guaranteed' },
  // '373': { coverageCode: 'ULJ', coverageDesc: '	Universal Life-Joint' },
  "52": { coverageCode: CoverageCode.UMB, coverageDesc: "	Umbrella-Personal" },
  // '416': { coverageCode: 'UND', coverageDesc: '	Underground Resources' },
  "359": {
    coverageCode: CoverageCode.UNI,
    coverageDesc: "	Life-Universal Life",
  },
  // '275': { coverageCode: 'UST', coverageDesc: '	Pollution- UST/AST' },
  // '414': { coverageCode: 'VAC', coverageDesc: '	Timesaver 4 (MMA)' },
  // '312': { coverageCode: 'VAD', coverageDesc: '	Voluntary AD&D' },
  // '375': { coverageCode: 'VAR', coverageDesc: '	Variable Annuity' },
  // '377': { coverageCode: 'VCA', coverageDesc: '	Voluntary Cancer' },
  "378": {
    coverageCode: CoverageCode.VCI,
    coverageDesc: "	Vol Critical Illness",
  },
  // '379': { coverageCode: 'VDE', coverageDesc: '	Voluntary Dental' },
  // '380': { coverageCode: 'VDL', coverageDesc: '	Voluntary Dep Life' },
  "163": { coverageCode: CoverageCode.VIS, coverageDesc: "	Vision" },
  // '381': { coverageCode: 'VL1', coverageDesc: '	Voluntary Life/AD&D' },
  // '382': { coverageCode: 'VL2', coverageDesc: '	Vol Life/AD&D/LTD Combo' },
  // '383': { coverageCode: 'VL3', coverageDesc: '	Voluntary Life/Dep Life' },
  // '230': { coverageCode: 'VLD', coverageDesc: '	Group Voluntary Ltd ' },
  "311": { coverageCode: CoverageCode.VLI, coverageDesc: "	Voluntary Life" },
  // '385': { coverageCode: 'VPO', coverageDesc: '	Voluntary Products-Other' },
  // '231': { coverageCode: 'VSD', coverageDesc: '	Group Voluntary Std' },
  // '387': { coverageCode: 'VSL', coverageDesc: '	Voluntary Supp Life' },
  // '386': { coverageCode: 'VST', coverageDesc: '	Voluntary STD' },
  // '384': { coverageCode: 'VTD', coverageDesc: '	Voluntary LTD' },
  // '26': { coverageCode: 'WAR', coverageDesc: '	A/R Workers Compensation' },
  "27": {
    coverageCode: CoverageCode.WCO,
    coverageDesc: "	Workers Compensation",
  },
  "286": {
    coverageCode: CoverageCode.WCP,
    coverageDesc: "	Work Comp-Personal Lines",
  },
  "139": {
    coverageCode: CoverageCode.WCS,
    coverageDesc: "	Workers Comp-Out of State",
  },
  // '388': { coverageCode: 'WDM', coverageDesc: '	Wellness/Disease Mgt' },
  // '123': { coverageCode: 'WEL', coverageDesc: '	Well Control' },
  "74": { coverageCode: CoverageCode.WIN, coverageDesc: "	Windstorm-Personal" },
  "389": { coverageCode: CoverageCode.WLI, coverageDesc: "	Whole Life-Indiv." },
  // '107': { coverageCode: 'WLL', coverageDesc: '	Warehouse Legal Liability' },
  // '322': { coverageCode: 'WLP', coverageDesc: '	Work Life Program' },
  // '189': { coverageCode: 'WPK', coverageDesc: '	Well Control Package' },
  // '238': { coverageCode: 'WRI', coverageDesc: '	War Risk Insurance' },
  "207": { coverageCode: CoverageCode.WRP, coverageDesc: "	Wrap Coverage" },
  // '119': { coverageCode: 'XCR', coverageDesc: '	Export Credit Insurance' },
  // '339': { coverageCode: 'XDI', coverageDesc: '	IND-Excess Disability' },
  // '191': { coverageCode: 'XDO', coverageDesc: '	Excess D & O' },
  // '179': { coverageCode: 'XFD', coverageDesc: '	Excess FDIC' },
  // '437': { coverageCode: 'XIM', coverageDesc: '	Excess Inland Marine' },
  "112": {
    coverageCode: CoverageCode.XLI,
    coverageDesc: "	Excess Liability-Comml",
  },
  "28": { coverageCode: CoverageCode.XLS, coverageDesc: "	Umbrella-Commercial" },
  // '284': { coverageCode: 'XMA', coverageDesc: '	Marine Excess Liability' },
  // '111': { coverageCode: 'XMT', coverageDesc: '	Maritime-Excess' },
  // '421': { coverageCode: 'XPD', coverageDesc: '	DONT USE' },
  // '129': { coverageCode: 'XPI', coverageDesc: '	Protection & Indem-Excess' },
  "122": {
    coverageCode: CoverageCode.XUM,
    coverageDesc: "	Umbrella-Excess-Comml",
  },
  "431": {
    coverageCode: CoverageCode.XUP,
    coverageDesc: "	Umbrella-Excess-Personal",
  },
  // '134': { coverageCode: 'XWC', coverageDesc: '	Non-Subscriber WC-Excess' },
  // '182': { coverageCode: 'XXX', coverageDesc: '	ERROR COVERAGE CODE' },
  XYX: {
    coverageCode: CoverageCode.XYX,
    coverageDesc: "Unimplemented Coverage Code",
  },
};

/**
 * Get coverage code information by coverage ID
 * @param coverageId The coverage ID to look up
 * @returns Coverage code information or default if not found
 */
export function getCoverageCodeById(
  coverageId: string | number | null | undefined
): { coverageCode: CoverageCode; coverageDesc: string } {
  if (!coverageId) {
    return {
      coverageCode: CoverageCode.XYX,
      coverageDesc: "Unimplemented Coverage Code",
    };
  }

  const coverageIdStr = coverageId.toString();
  return (
    coverageCodes[coverageIdStr] || {
      coverageCode: CoverageCode.XYX,
      coverageDesc: "Unimplemented Coverage Code",
    }
  );
}
