import { z } from "zod/v4";
import { accountSchema } from "../accounts/account.schema";

export const taskHistorySchema = z.object({
  active: z.boolean(),
  assignedTo: accountSchema,
  dateAvailable: z.date(),
  dateInitiated: z.date(),
  deadline: z.date().nullable(),
  debug: z.boolean(),
  documentAttributes: z.array(z.unknown()),
  documentDescription: z.string(),
  documentModifiedDate: z.date(),
  documentTypeName: z.string(),
  documentTypeDescription: z.string(),
  documentDateCaptured: z.date(),
  endTime: z.date().nullable(),
  fileAttributes: z.array(z.unknown()),
  fileId: z.number(),
  fileName: z.string(),
  fileNumber: z.string(),
  fileNumber2: z.string(),
  fileNumber3: z.string(),
  fileTypeDescription: z.string(),
  fileTypeName: z.string(),
  flowName: z.string(),
  folderAttributes: z.array(z.unknown()),
  folderDescription: z.string(),
  folderTypeName: z.string(),
  folderTypeDescription: z.string(),
  hasNotes: z.boolean(),
  isTemporary: z.boolean(),
  latestOperation: z.date(),
  locationName: z.string(),
  noteId: z.number().nullable(),
  objectId: z.number(),
  operation: z.string(),
  operationByUser: accountSchema,
  operationTime: z.date(),
  pageDescription: z.string().nullable(),
  pageId: z.number().nullable(),
  priority: z.number(),
  routedToStep: z.number(),
  startTime: z.date(),
  status: z.string(),
  stepId: z.number(),
  stepName: z.string(),
  taskId: z.number(),
  taskDescription: z.string(),
  attributeHistory: z.array(z.unknown()),
});

export type TaskHistory = z.infer<typeof taskHistorySchema>;