import { z } from "zod/v4";

export const glUnderwritingSchema = z
  .object({
    GL_UNDERWRITING_ID: z.number().optional().nullable(),
    BLASTINGEXPLOSIVESUSEDSTORE: z.string().optional().nullable(),
    CLAIMSMADEENTRYDATE: z.date().optional().nullable(),
    DATEOFF: z.date().optional().nullable(),
    FULLTIMESTAFF: z.string().optional().nullable(),
    LEASED: z.string().optional().nullable(),
    NY855BLANKETLIAB_NC: z.string().optional().nullable(),
    NY855BLANKETLIAB_NO: z.string().optional().nullable(),
    NY855BLANKETLIAB_YES: z.string().optional().nullable(),
    NY855CLAIMSINJURY_NA: z.string().optional().nullable(),
    NY855CLAIMSINJURY_NC: z.string().optional().nullable(),
    NY855CLAIMSINJURY_YES: z.string().optional().nullable(),
    NY855EARTHMOVEMENT_NA: z.string().optional().nullable(),
    NY855EARTHMOVEMENT_NC: z.string().optional().nullable(),
    NY855EARTHMOVEMENT_YES: z.string().optional().nullable(),
    NY855EXCLREMOVED_NA: z.string().optional().nullable(),
    NY855EXCLREMOVED_NC: z.string().optional().nullable(),
    NY855EXCLREMOVED_YES: z.string().optional().nullable(),
    NY855GLPOLICYFORM_ISO: z.string().optional().nullable(),
    NY855GLPOLICYFORM_OTHER: z.string().optional().nullable(),
    NY855INSCANCELS_NA: z.string().optional().nullable(),
    NY855INSCANCELS_NO: z.string().optional().nullable(),
    NY855INSCANCELS_YES: z.string().optional().nullable(),
    NY855INSENDOTHER: z.string().optional().nullable(),
    NY855INSENDOTHER_NUM: z.string().optional().nullable(),
    NY855INSENDOTHER_TITLE: z.string().optional().nullable(),
    NY855INSEND_CG2010: z.string().optional().nullable(),
    NY855INSEND_CG2026: z.string().optional().nullable(),
    NY855INSEND_CG2032: z.string().optional().nullable(),
    NY855INSEND_CG2033: z.string().optional().nullable(),
    NY855INSEND_CG2037: z.string().optional().nullable(),
    NY855INSEND_CG2038: z.string().optional().nullable(),
    NY855INSURER_ADMITTED: z.string().optional().nullable(),
    NY855INSURER_EXCESS: z.string().optional().nullable(),
    NY855LIABISOCGL_NA: z.string().optional().nullable(),
    NY855LIABISOCGL_NC: z.string().optional().nullable(),
    NY855LIABISOCGL_YES: z.string().optional().nullable(),
    NY855PRIMCOV_NA: z.string().optional().nullable(),
    NY855PRIMCOV_NO: z.string().optional().nullable(),
    NY855PRIMCOV_YES: z.string().optional().nullable(),
    NY855SPECOPSBUILDINGHGT: z.string().optional().nullable(),
    NY855SPECOPSBUILDINGHGT_INFO: z.string().optional().nullable(),
    NY855SPECOPSCLASS: z.string().optional().nullable(),
    NY855SPECOPSCONSTTYPE: z.string().optional().nullable(),
    NY855SPECOPSCONSTTYPE_INFO: z.string().optional().nullable(),
    NY855SPECOPSDESIGNWK: z.string().optional().nullable(),
    NY855SPECOPSLOC: z.string().optional().nullable(),
    NY855SPECOPSLOC_INFO: z.string().optional().nullable(),
    NY855UMBRPOL_END: z.string().optional().nullable(),
    NY855UMBRPOL_NA: z.string().optional().nullable(),
    NY855UMBRPOL_NO: z.string().optional().nullable(),
    NY855UMBRPOL_SPEC: z.string().optional().nullable(),
    NY855WORKEXCL_NA: z.string().optional().nullable(),
    NY855WORKEXCL_NC: z.string().optional().nullable(),
    NY855WORKEXCL_YES: z.string().optional().nullable(),
    PARTTIMESTAFF: z.string().optional().nullable(),
    PLANSDESIGNSSPECS: z.string().optional().nullable(),
    POLICIES_ID: z.number().optional().nullable(),
    PRODWORKACCLOCEXCLUNINSURED: z.string().optional().nullable(),
    RETRODATE: z.date().optional().nullable(),
    SUBCERTS: z.string().optional().nullable(),
    SUBCONTRACTEDWORKDESCRIPTION: z.string().optional().nullable(),
    SUBCONTRPERCENT: z.string().optional().nullable(),
    SUBCOV: z.string().optional().nullable(),
    TAILCOVERAGE: z.string().optional().nullable(),
    TUNNEL: z.string().optional().nullable(),
    URISEQ: z.string().optional().nullable(),
  })
  .meta({
    description:
      "General liability underwriting from Sagitta table 'GL_UNDERWRITING'",
    sagittaTable: "GL_UNDERWRITING",
  });

export type GlUnderwritingSchema = z.infer<typeof glUnderwritingSchema>;
