import { z } from "zod/v4";

export enum CoverageCode {
  PLL = "PLL",
  FPK = "FPK",
  DEN = "DEN",
  EPL = "EPL",
  WRP = "WRP",
  BLK = "BLK",
  PKP = "PKP",
  CFO = "CFO",
  STO = "STO",
  MOT = "MOT",
  HNO = "HNO",
  AUT = "AUT",
  CON = "CON",
  APP = "APP",
  LAD = "LAD",
  PRM = "PRM",
  HEA = "HEA",
  DPP = "DPP",
  PFL = "PFL",
  XUP = "XUP",
  LIQ = "LIQ",
  PFE = "PFE",
  HOM = "HOM",
  WLI = "WLI",
  ERI = "ERI",
  DWL = "DWL",
  PBR = "PBR",
  TVL = "TVL",
  FID = "FID",
  BNO = "BNO",
  MGL = "MGL",
  ILT = "ILT",
  RRP = "RRP",
  BLR = "BLR",
  XLI = "XLI",
  TT = "TT",
  EEO = "EEO",
  BDR = "BDR",
  GLI = "GLI",
  LOS = "LOS",
  D_O = "D&O",
  PRO = "PRO",
  ELP = "ELP",
  PEO = "PEO",
  KIP = "KIP",
  ACC = "ACC",
  PLB = "PLB",
  CIM = "CIM",
  EDO = "EDO",
  EFL = "EFL",
  BMI = "BMI",
  DED = "DED",
  MPP = "MPP",
  CPL = "CPL",
  CPP = "CPP",
  EQF = "EQF",
  GPK = "GPK",
  FLE = "FLE",
  PRF = "PRF",
  LTD = "LTD",
  PKC = "PKC",
  MIC = "MIC",
  FAR = "FAR",
  CWI = "CWI",
  CWE = "CWE",
  REC = "REC",
  GLP = "GLP",
  WCO = "WCO",
  BCO = "BCO",
  WIN = "WIN",
  BOP = "BOP",
  VCI = "VCI",
  MIP = "MIP",
  IND = "IND",
  PIM = "PIM",
  MPK = "MPK",
  GRL = "GRL",
  CRM = "CRM",
  INT = "INT",
  BOA = "BOA",
  WCP = "WCP",
  PKG = "PKG",
  UMB = "UMB",
  OMA = "OMA",
  RMC = "RMC",
  TRK = "TRK",
  WCS = "WCS",
  UNI = "UNI",
  CBI = "CBI",
  XLS = "XLS",
  PKM = "PKM",
  PKN = "PKN",
  CAU = "CAU",
  PEN = "PEN",
  FDC = "FDC",
  CFL = "CFL",
  POL = "POL",
  STM = "STM",
  VIS = "VIS",
  CWA = "CWA",
  GAR = "GAR",
  DPK = "DPK",
  MOB = "MOB",
  MAR = "MAR",
  FAP = "FAP",
  GLA = "GLA",
  XUM = "XUM",
  TRN = "TRN",
  PFA = "PFA",
  TEN = "TEN",
  BTA = "BTA",
  STD = "STD",
  MHM = "MHM",
  CYB = "CYB",
  MDE = "MDE",
  GDE = "GDE",
  BEN = "BEN",
  VLI = "VLI",
  P_I = "P&I",
  MTI = "MTI",
  MCS = "MCS",
  PPK = "PPK",
  EDP = "EDP",
  OCP = "OCP",
  XYX = "XYX",
  FLT = "FLT",
  MCR = "MCR",
  MISC = "MISC",
}

export const policiesSchema = z.object({
  POLICIES_ID: z.number().optional().nullable(),
  ANNUALAGENCYCOMM: z.any().optional().nullable(),
  ANNUALPREMIUM: z.any().optional().nullable(),
  ANNUALPRODCOMM: z.number().optional().nullable(),
  AUDITCODE: z.string().optional().nullable(),
  AUTOCLUBMEMBER: z.string().optional().nullable(),
  BENEFITS_LIFE_ONLY_EST_ANNUAL_COMMISSION_ADDL: z
    .number()
    .optional()
    .nullable(),
  BILLTO_ID: z.number().optional().nullable(),
  BILLTOCODE: z.string().optional().nullable(),
  BILLTONAME: z.string().optional().nullable(),
  BILLTYPE: z.string().optional().nullable(),
  BINDEREFFDATE: z.date().optional().nullable(),
  BINDEREFFTIME: z.string().optional().nullable(),
  BINDEREXPDATE: z.date().optional().nullable(),
  BINDEREXPTIME: z.string().optional().nullable(),
  BINDERREASON: z.string().optional().nullable(),
  BINDER_OR_POLICY_STATUS_REMARKS_ADDL: z.string().optional().nullable(),
  BINDER_RECEIVED_ADDL: z.string().optional().nullable(),
  BLOCKDOWNLOAD: z.string().optional().nullable(),
  CANCELDATE: z.date().optional().nullable(),
  CANCELEVIDENCE: z.string().optional().nullable(),
  CANCELMETHOD: z.string().optional().nullable(),
  CANCELREASON: z.string().optional().nullable(),
  CARRPRODSUBCD: z.string().optional().nullable(),
  CLIENTCODE: z.string().optional().nullable(),
  CLIENTNAME: z.string().optional().nullable(),
  CLIENTS_ID: z.number().optional().nullable(),
  CNR: z.string().optional().nullable(),
  CNRDATE: z.date().optional().nullable(),
  COINSURED_SSN: z.string().optional().nullable(),
  COINSUREDSDATEOFBIRTH: z.date().optional().nullable(),
  COINSUREDSEMPLOYERSNAME: z.string().optional().nullable(),
  COINSUREDSMARITALSTATUSCODE: z.string().optional().nullable(),
  COINSUREDSOCCCUPATION: z.string().optional().nullable(),
  COINSUREDSOCCUPATIONCODE: z.string().optional().nullable(),
  COINSUREDSSOCIALSECURITY: z.any().optional().nullable(),
  COINSUREDSYRSCURRENTEMPLOYER: z.string().optional().nullable(),
  COINSUREDYRPREVEMPLOYER: z.string().optional().nullable(),
  COINSUREDYRSCURROCCUPATION: z.string().optional().nullable(),
  COVCODE: z.enum(CoverageCode).nullable().optional(),
  COVERAGES_ID: z.number().optional().nullable(),
  DATEBUSINESSSTARTED: z.date().optional().nullable(),
  DATECURRENTADDRESS: z.date().optional().nullable(),
  DATEPREVIOUSADDRESS: z.date().optional().nullable(),
  DEPARTMENT_CODE: z.string().optional().nullable(),
  DESCRIPTION: z.string().optional().nullable(),
  DIVISION_CODE: z.number().optional().nullable(),
  EFFDATE: z.date().optional().nullable(),
  EFFTIME: z.string().optional().nullable(),
  ENTRYDATE: z.date().optional().nullable(),
  EST_COMM_AMT: z.any().optional().nullable(),
  EST_COMM_PCT: z.any().optional().nullable(),
  EST_PREM_AMT: z.any().optional().nullable(),
  EXPDATE: z.date().optional().nullable(),
  EXPTIME: z.string().optional().nullable(),
  GENINFOREMARKS: z.string().optional().nullable(),
  IF_FINANCED_PREMIUM_FINANCE_ACCT_NUMBER_ADDL: z
    .string()
    .optional()
    .nullable(),
  INSCODE: z.string().optional().nullable(),
  INSTALLMENTFLAG: z.string().optional().nullable(),
  INSURED_SSN: z.string().optional().nullable(),
  INSUREDSDATEOFBIRTH: z.date().optional().nullable(),
  INSUREDSEMPLOYERSNAME: z.string().optional().nullable(),
  INSUREDSMARITALSTATUS: z.string().optional().nullable(),
  INSUREDSOCCUPATION: z.string().optional().nullable(),
  INSUREDSOCCUPATIONCODE: z.string().optional().nullable(),
  INSUREDSSOCIALSECURITY: z.string().optional().nullable(),
  INSUREDYRSCURRENTEMPLOYER: z.string().optional().nullable(),
  INSUREDYRSPREVEMPLOYER: z.string().optional().nullable(),
  INSURORS_ID: z.number().optional().nullable(),
  INSURERNAME: z.string().optional().nullable(),
  LAST_CHANGE: z.number().optional().nullable(),
  LASTCOMM: z.any().optional().nullable(),
  LASTCOMMAMT: z.any().optional().nullable(),
  LASTEFFDATE: z.date().optional().nullable(),
  LASTENTRYDATE: z.date().optional().nullable(),
  LASTPREMIUM: z.any().optional().nullable(),
  LASTTRAN: z.string().optional().nullable(),
  LASTTRANDATE: z.date().optional().nullable(),
  LASTUSER: z.string().optional().nullable(),
  MAJORLINE: z.string().optional().nullable(),
  NAMEDINDIVIDUALS: z.string().optional().nullable(),
  NAMEDINSURED: z.string().optional().nullable(),
  NEWREN: z.string().optional().nullable(),
  NEXT_POL_ANN_PREM: z.number().optional().nullable(),
  NEXT_POL_ANN_PROD_COMM: z.number().optional().nullable(),
  NEXT_POL_INS: z.string().optional().nullable(),
  NEXT_POL_NUM: z.string().optional().nullable(),
  NEXTPOLICYID: z.any().optional().nullable(),
  ORIGINCEPT: z.date().optional().nullable(),
  PAYEES_ID: z.string().optional().nullable(),
  PAYEES_NAME: z.string().optional().nullable(),
  POLICY_DESCRIPTION: z.string().optional().nullable(),
  POLICY_NOTE: z.string().optional().nullable(),
  POLICY_SOURCE: z.string().optional().nullable(),
  POLICYNUMBER: z.string().optional().nullable(),
  POLICYREMARKS: z.string().optional().nullable(),
  POLICYREMARKS2: z.string().optional().nullable(),
  PREMIUM_FINANCE_CO_ADDL: z.string().optional().nullable(),
  PREVADDRESS: z.string().optional().nullable(),
  PREVADDRESS2: z.string().optional().nullable(),
  PREVCITY: z.string().optional().nullable(),
  PREVPOLICYID: z.string().optional().nullable(),
  PREVSTATE: z.string().optional().nullable(),
  PROD1: z.string().optional().nullable(),
  PROD2: z.string().optional().nullable(),
  PROD3: z.string().optional().nullable(),
  PRODNAME1: z.string().optional().nullable(),
  PRODNAME2: z.string().optional().nullable(),
  PRODNAME3: z.string().optional().nullable(),
  REGION: z.string().optional().nullable(),
  REGIONNAME: z.string().optional().nullable(),
  REINSTATEDATE: z.date().optional().nullable(),
  REINSTATEREASON: z.string().optional().nullable(),
  RESIDENTRELATIVES: z.string().optional().nullable(),
  SEPARATE_EQUIP_SCHEDULE_FILED_IN_CBD_ADDL: z.string().optional().nullable(),
  SEPARATE_PROPERTY_SCHEDULE_FILED_IN_CBD_ADDL: z
    .string()
    .optional()
    .nullable(),
  SERV1NAME: z.string().optional().nullable(),
  SERV2NAME: z.string().optional().nullable(),
  SERV3NAME: z.string().optional().nullable(),
  SERVICER_CODE: z.string().optional().nullable(),
  SICCODE: z.number().optional().nullable(),
  STATE: z.string().optional().nullable(),
  TERM: z.string().optional().nullable(),
  TOTALHOUSEHOLDINCOME: z.number().optional().nullable(),
  UMPDREJECTION: z.string().optional().nullable(),
  UNDERINSMOTORISTREJECTION: z.string().optional().nullable(),
  VEHICLESINHOUSEHOLD: z.string().optional().nullable(),
  WRITTENAGENCYCOMM: z.any().optional().nullable(),
  WRITTENPREMIUM: z.any().optional().nullable(),
  WRITTENPRODCOMM: z.number().optional().nullable(),
  YEARSINBUSINESS: z.number().optional().nullable(),
  YRSCURRENTADDRESS: z.string().optional().nullable(),
  YRSCURRENTOCCUPATION: z.string().optional().nullable(),
  YRSKNOWBYAGENTBROKER: z.string().optional().nullable(),
  APPROVED: z.boolean().optional().nullable(),
  COMPLETION_PERCENTAGE: z.number().optional().nullable(),
  TABLES_WITHOUT_LOCKED_RECORDS: z.array(z.string()).optional().nullable(),
  TABLES_WITH_RECORDS: z.array(z.string()).optional().nullable(),
  TOTAL_RECORDS: z.number().optional().nullable(),
  TOTAL_LOCKED_RECORDS: z.number().optional().nullable(),
});

export type PoliciesSchema = z.infer<typeof policiesSchema>;
