import { z } from "zod/v4";

export const umCoveragesSchema = z
  .object({
    ADDINTCOVERAGE: z.string().optional().nullable(),
    ADDINTEXPOSURE: z.string().optional().nullable(),
    AIRCRAFTLIABCOVERAGE: z.string().optional().nullable(),
    AIRCRAFTLIABEXPOSURE: z.string().optional().nullable(),
    AIRCRAFTPASSCOVERAGE: z.string().optional().nullable(),
    AIRCRAFTPASSEXPOSURE: z.string().optional().nullable(),
    CARECUSTODYCOVERAGE: z.string().optional().nullable(),
    CARECUSTODYEXPOSURE: z.string().optional().nullable(),
    COVERAGEEXTENTIONSCREEN: z.string().optional().nullable(),
    COVSEQ: z.string().optional().nullable(),
    CURRENTRETRODATE: z.date().optional().nullable(),
    DATEOFF: z.date().optional().nullable(),
    DESCOFUNDERLYINGCOV: z.string().optional().nullable(),
    EMPBENEFITCOVERAGE: z.string().optional().nullable(),
    EMPBENEFITEXPOSURE: z.string().optional().nullable(),
    FIRSTDOLLARDEFENSE: z.string().optional().nullable(),
    FIRSTOTHERCOVERAGE: z.string().optional().nullable(),
    FIRSTOTHERDESCRIPTION: z.string().optional().nullable(),
    FIRSTOTHEREXPOSURE: z.string().optional().nullable(),
    FOLLOWFORMEXCESS: z.string().optional().nullable(),
    FOLLOWUMBFORM: z.string().optional().nullable(),
    FOREIGNLIABCOVERAGE: z.string().optional().nullable(),
    FOREIGNLIABEXPOSURE: z.string().optional().nullable(),
    FOURTHOTHERCOVERAGE: z.string().optional().nullable(),
    FOURTHOTHERDESCRIPTION: z.string().optional().nullable(),
    FOURTHOTHEREXPOSURE: z.string().optional().nullable(),
    GARAGEKEEPERSCOVERAGE: z.string().optional().nullable(),
    GARAGEKEEPERSEXPOSURE: z.string().optional().nullable(),
    LIABANNUALAGGREGATE: z.number().optional().nullable(),
    LIABEACHOCCURLIMIT: z.number().optional().nullable(),
    LIQUORCOVERAGE: z.string().optional().nullable(),
    LIQUOREXPOSURE: z.string().optional().nullable(),
    MALPRACTICECOVERAGE: z.string().optional().nullable(),
    MALPRACTICEEXPOSURE: z.string().optional().nullable(),
    POLICIES_ID: z.number().optional().nullable(),
    POLLUTIONCOVERAGE: z.string().optional().nullable(),
    POLLUTIONEXPOSURE: z.string().optional().nullable(),
    PROFESSIONALCOVERAGE: z.string().optional().nullable(),
    PROFESSIONALEXPOSURE: z.string().optional().nullable(),
    RETAINEDLIMIT: z.number().optional().nullable(),
    SECONDOTHERCOVERAGE: z.string().optional().nullable(),
    SECONDOTHERDESCRIPTION: z.string().optional().nullable(),
    SECONDOTHEREXPOSURE: z.string().optional().nullable(),
    THIRDOTHERCOVERAGE: z.string().optional().nullable(),
    THIRDOTHERDESCRIPTION: z.string().optional().nullable(),
    THIRDOTHEREXPOSURE: z.string().optional().nullable(),
    UM_COVERAGES_ID: z.number().optional().nullable(),
    UMBRELLAEXCESS: z.string().optional().nullable(),
    UNDERLYINGCGLMISCSCREEN: z.string().optional().nullable(),
    VENDORSLIABCOVERAGE: z.string().optional().nullable(),
    VENDORSLIABEXPOSURE: z.string().optional().nullable(),
    WATERCRAFTCOVERAGE: z.string().optional().nullable(),
    WATERCRAFTEXPOSURE: z.string().optional().nullable(),
  })
  .meta({
    description: "Umbrella coverages from Sagitta table 'UM_COVERAGES'",
    sagittaTable: "UM_COVERAGES",
  });

export type UMCoveragesSchema = z.infer<typeof umCoveragesSchema>;
