import z from "zod/v4";

export const clientsSchema: z.ZodSchema = z
  .object({
    CLIENTS_ID: z.number().int(),
    ACCTINGCONTACT: z.string().nullable().optional(),
    ACCTINGEXTENSION: z.string().nullable().optional(),
    ACCTPHONENUMBER: z.string().nullable().optional(),
    ADDRESS1: z.string().nullable().optional(),
    ADDRESS2: z.string().nullable().optional(),
    BENEFITS_ACCOUNT_EXECUTIVE_ADDL: z.string().nullable().optional(),
    BENEFITS_ACCOUNT_MANAGER_ADDL: z.string().nullable().optional(),
    BILLTO_ID: z.number().int().nullable().optional(),
    BILLTOADDRESS1: z.string().nullable().optional(),
    BILLTOADDRESS2: z.string().nullable().optional(),
    BILLTOCITY: z.string().nullable().optional(),
    BILLTOCODE: z.string().nullable().optional(),
    BILLTONAME: z.string().nullable().optional(),
    BILLTOSTATE: z.string().nullable().optional(),
    BILLTOZIPCODE: z.string().nullable().optional(),
    BOND_ACCOUNT_EXECUTIVE_ADDL: z.string().nullable().optional(),
    BOND_ACCOUNT_MANAGER_ADDL: z.string().nullable().optional(),
    CATCODE1: z.string().nullable().optional(),
    CATCODE2: z.string().nullable().optional(),
    CATCODE3: z.string().nullable().optional(),
    CATCODE4: z.string().nullable().optional(),
    CATCODE5: z.string().nullable().optional(),
    CITY: z.string().nullable().optional(),
    CLAIMS_FILE_REVIEW_ADDL: z.string().nullable().optional(),
    CLAIMS_FILE_REVIEW_PERIOD_ADDL: z.string().nullable().optional(),
    CLIENT_CODE: z.string().nullable().optional(),
    CLIENT_NOTE: z.string().nullable().optional(),
    CLIENTNAME: z.string().nullable().optional(),
    COLLECTIONCOMMENTS: z.string().nullable().optional(),
    COMMENTARY: z.string().nullable().optional(),
    COMMERCIAL_AM_PROCESSOR_ADDL: z.string().nullable().optional(),
    COMPLEXITY_RATING_ADDL: z.string().nullable().optional(),
    CREDITTERMS: z.string().nullable().optional(),
    DATEBUSINESSSTARTED: z.date().nullable().optional(),
    DIVISION_CODE: z.string().nullable().optional(),
    EMAILADDRESS: z.string().nullable().optional(),
    FAXNUMBER: z.string().nullable().optional(),
    FEIN: z.string().nullable().optional(),
    INSPECTIONCONTACT: z.string().nullable().optional(),
    INSPECTIONEXTENSION: z.number().nullable().optional(),
    INSPECTIONPHONENUMBER: z.number().nullable().optional(),
    LASTENTRYDATE: z.date().nullable().optional(),
    LASTUSER: z.string().nullable().optional(),
    LEGALENTITY: z.string().nullable().optional(),
    MANAGEMENT_LIABILITY_TEAM_ACCT_MGR_ADDL: z.string().nullable().optional(),
    NETCOMM: z.number().nullable().optional(),
    PARRISH_ADDL: z.string().nullable().optional(),
    PHONEEXT1: z.number().nullable().optional(),
    PHONEEXT2: z.number().nullable().optional(),
    PROD1: z.string().nullable().optional(),
    PROD2: z.string().nullable().optional(),
    PROD3: z.string().nullable().optional(),
    QUALITY_CONTROL_DATE_ADDL: z.date().nullable().optional(),
    REFERENCECODE: z.string().nullable().optional(),
    SERV1: z.string().nullable().optional(),
    SERV2: z.string().nullable().optional(),
    SERV3: z.string().nullable().optional(),
    SICCODE1: z.number().nullable().optional(),
    SICCODE2: z.number().nullable().optional(),
    SICCODE3: z.number().nullable().optional(),
    SOURCE: z.string().nullable().optional(),
    SOURCEDATE: z.date().nullable().optional(),
    STATE: z.string().nullable().optional(),
    STATUS1: z.string().nullable().optional(),
    STATUS2: z.string().nullable().optional(),
    STATUS3: z.string().nullable().optional(),
    TELEPHONE1: z.string().nullable().optional(),
    TELEPHONE2: z.string().nullable().optional(),
    WEBSITE: z.string().nullable().optional(),
    YEARSINBUSINESS: z.number().nullable().optional(),
    ZIPCODE: z.string().nullable().optional(),
    ZIPCODEEXT: z.string().nullable().optional(),
    BENEFIT_ACCOUNT_MANAGER_ADDL: z.string().nullable().optional(),
    BENEFIT_CLIENT_LIAISON_ADDL: z.string().nullable().optional(),
    BENEFIT_ACCOUNT_EXECUTIVE_ADDL: z.string().nullable().optional(),
  })
  .meta({
    description: "Clients from Sagitta table 'CLIENTS'",
    sagittaTable: "CLIENTS",
  });

export type ClientsSchema = z.infer<typeof clientsSchema>;
