import { z } from "zod/v4";

export const baCoveragesSchema = z
  .object({
    BA_COVERAGES_ID: z.number().nullable().optional(),
    ADDLPIPDEDUCTIBLE: z.number().nullable().optional(),
    ADDLPIPLIMIT: z.number().nullable().optional(),
    ADDLPIPPREMIUM: z.number().nullable().optional(),
    ADDLPIPSYMBOL1: z.string().nullable().optional(),
    ADDLPIPSYMBOL2: z.string().nullable().optional(),
    COLLISIONDED: z.number().nullable().optional(),
    COLLISIONLIMIT: z.number().nullable().optional(),
    COLLISIONPREM: z.number().nullable().optional(),
    COLLISIONSYMBOL1: z.string().nullable().optional(),
    COLLISIONSYMBOL2: z.string().nullable().optional(),
    COLLISIONSYMBOL3: z.string().nullable().optional(),
    COLLISIONSYMBOL4: z.string().nullable().optional(),
    COMBINEDPDDEDUCTIBLE: z.number().nullable().optional(),
    COMBINEDPDLIMIT: z.number().nullable().optional(),
    COMBINEDPDPREMIUM: z.number().nullable().optional(),
    COMBINEDPDSYMBOL1: z.string().nullable().optional(),
    COMBINEDPDSYMBOL2: z.string().nullable().optional(),
    COMBINEDPDSYMBOL3: z.string().nullable().optional(),
    COMBINEDPDSYMBOL4: z.string().nullable().optional(),
    COMPREHENSIVEDED: z.number().nullable().optional(),
    COMPREHENSIVELIMIT: z.number().nullable().optional(),
    COMPREHENSIVEPREM: z.number().nullable().optional(),
    COMPREHENSIVESYMBOL1: z.string().nullable().optional(),
    COMPREHENSIVESYMBOL2: z.string().nullable().optional(),
    COMPREHENSIVESYMBOL3: z.string().nullable().optional(),
    COMPREHENSIVESYMBOL4: z.string().nullable().optional(),
    DATEOFF: z.date().nullable().optional(),
    LASTEFFDATE: z.date().nullable().optional(),
    LASTENTRYDATE: z.date().nullable().optional(),
    LIABILITYDED: z.number().nullable().optional(),
    LIABILITYLIMITS1: z.number().nullable().optional(),
    LIABILITYLIMITS2: z.number().nullable().optional(),
    LIABILITYPREM: z.number().nullable().optional(),
    LIABILITYSYMBOL1: z.string().nullable().optional(),
    LIABILITYSYMBOL2: z.string().nullable().optional(),
    LIABILITYSYMBOL3: z.string().nullable().optional(),
    LIABILITYSYMBOL4: z.string().nullable().optional(),
    LIABILITYSYMBOL5: z.string().nullable().optional(),
    MPDED: z.number().nullable().optional(),
    MPLIMIT: z.number().nullable().optional(),
    MPPREM: z.number().nullable().optional(),
    MPSYMBOL1: z.string().nullable().optional(),
    MPSYMBOL2: z.string().nullable().optional(),
    MPSYMBOL3: z.string().nullable().optional(),
    PDDED: z.number().nullable().optional(),
    PDLIMIT: z.number().nullable().optional(),
    PDPREM: z.number().nullable().optional(),
    PIPDED: z.number().nullable().optional(),
    PIPLIMIT: z.number().nullable().optional(),
    PIPPREM: z.number().nullable().optional(),
    PIPSYMBOL1: z.string().nullable().optional(),
    PIPSYMBOL2: z.string().nullable().optional(),
    PIPSYMBOL3: z.string().nullable().optional(),
    POLICIES_ID: z.number().nullable().optional(),
    SPECIFIEDPERILDEDUCTIBLE: z.number().nullable().optional(),
    SPECIFIEDPERILLIMIT: z.number().nullable().optional(),
    SPECIFIEDPERILPREMIUM: z.number().nullable().optional(),
    SPECIFIEDPERILSYMBOL1: z.string().nullable().optional(),
    SPECIFIEDPERILSYMBOL2: z.string().nullable().optional(),
    SPECIFIEDPERILSYMBOL3: z.string().nullable().optional(),
    SPECIFIEDPERILSYMBOL4: z.string().nullable().optional(),
    TOWINGANDLABORDEDUCTIBLE: z.number().nullable().optional(),
    TOWINGANDLABORLIMIT: z.number().nullable().optional(),
    TOWINGANDLABORPREMIUM: z.number().nullable().optional(),
    TOWINGANDLABORSYMBOL1: z.string().nullable().optional(),
    TOWINGANDLABORSYMBOL2: z.string().nullable().optional(),
    TOWINGANDLABORSYMBOL3: z.string().nullable().optional(),
    UNDERINSUREDDED: z.number().nullable().optional(),
    UNDERINSUREDDEDPD: z.number().nullable().optional(),
    UNDERINSUREDLIMIT1: z.number().nullable().optional(),
    UNDERINSUREDLIMIT2: z.number().nullable().optional(),
    UNDERINSUREDLIMITPD: z.number().nullable().optional(),
    UNDERINSUREDPREM: z.number().nullable().optional(),
    UNDERINSUREDPREMPD: z.number().nullable().optional(),
    UNDERINSUREDSYMBOL1: z.string().nullable().optional(),
    UNDERINSUREDSYMBOL2: z.string().nullable().optional(),
    UNDERINSUREDSYMBOL3: z.string().nullable().optional(),
    UNINSUREDDED: z.number().nullable().optional(),
    UNINSUREDDEDPD: z.number().nullable().optional(),
    UNINSUREDLIMIT1: z.number().nullable().optional(),
    UNINSUREDLIMIT2: z.number().nullable().optional(),
    UNINSUREDLIMITPD: z.number().nullable().optional(),
    UNINSUREDPREM: z.number().nullable().optional(),
    UNINSUREDPREMPD: z.number().nullable().optional(),
    UNINSUREDSYMBOL1: z.string().nullable().optional(),
    UNINSUREDSYMBOL2: z.string().nullable().optional(),
    UNINSUREDSYMBOL3: z.string().nullable().optional(),
  })
  .meta({
    description: "Auto coverages from Sagitta table 'BA_COVERAGES'",
    sagittaTable: "BA_COVERAGES",
  });

export type BACoveragesSchema = z.infer<typeof baCoveragesSchema>;
