import z from "zod/v4";
export const staff = z.object({
    ADDRESS1: z.string().nullable().optional(),
    ADDRESS2: z.string().nullable().optional(),
    AGENCYCODE: z.string().nullable().optional(),
    ANNUALSALARY: z.number().nullable().optional(),
    AUTHORID: z.string().nullable().optional(),
    BIRTHDAY: z.date().nullable().optional(),
    CITY: z.string().nullable().optional(),
    CONO: z.string().nullable().optional(),
    DATEHIRED: z.string().nullable().optional(),
    DATEOFF: z.string().nullable().optional(),
    DATEOFFREMARKS: z.string().nullable().optional(),
    DEPT: z.string().nullable().optional(),
    DISPLAY_ONLY: z.string().nullable().optional(),
    DIVISIONNO: z.string().nullable().optional(),
    EMAILADDRESS: z.string().nullable().optional(),
    EMERPHONE: z.string().nullable().optional(),
    FAXPRIORITY: z.string().nullable().optional(),
    HOMEPAGE_ROLE: z.string().nullable().optional(),
    HOMEPHONE: z.string().nullable().optional(),
    LASTENTRYDATE: z.string().nullable().optional(),
    LASTUSER: z.string().nullable().optional(),
    NEXTREVIEW: z.string().nullable().optional(),
    OMITREADSCREENS: z.string().nullable().optional(),
    SECURITY_ROLE: z.string().nullable().optional(),
    SKIP: z.string().nullable().optional(),
    SOCIALSECURITY: z.string().nullable().optional(),
    ST: z.string().nullable().optional(),
    STAFF_ID: z.string(),
    STAFFCODE: z.string().nullable().optional(),
    STAFFNAME: z.string().nullable().optional(),
    STAFFTITLE: z.string().nullable().optional(),
    STATE: z.string().nullable().optional(),
    SUPERUSER: z.string().nullable().optional(),
    TERMDATE: z.string().nullable().optional(),
    USER_ID: z.string().nullable().optional(),
    WORKFLOW_MAND: z.string().nullable().optional(),
    WORKPHONE: z.string().nullable().optional(),
    XXXSTAFF_ID: z.string().nullable().optional(),
    ZIPCODE: z.string().nullable().optional(),
    ZIPCODEEXT: z.string().nullable().optional(),
});

export type Staff = z.infer<typeof staff>;